# Generated by Django 5.0.2 on 2024-03-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebookdesign',
            name='contact_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
