# Generated by Django 5.0.2 on 2024-04-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbuy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartbuy',
            name='user',
        ),
        migrations.DeleteModel(
            name='NeededProducts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='CartBuy',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Items',
        ),
    ]
