# Generated by Django 5.0.1 on 2024-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0002_agentproducts_agentproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentProducts',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], default='customer', max_length=20),
        ),
    ]
