# Generated by Django 5.0.2 on 2024-03-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0003_productbuy_delete_wishlistlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbuy',
            old_name='apartement',
            new_name='apartment',
        ),
        migrations.AddField(
            model_name='productbuy',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
