# Generated by Django 5.0.1 on 2024-02-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproduct',
            name='catgory',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('bedroom', 'Bedroom'), ('diningroom', 'Diningroom'), ('reception', 'Reception'), ('pantry', 'Pantry'), ('meetingroom', 'Meetingroom'), ('shoproom', 'Shoproom')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentproduct',
            name='propertytype',
            field=models.CharField(choices=[('home', 'Home'), ('shop', 'Shop'), ('office', 'Office')], max_length=1000, null=True),
        ),
    ]
