# Generated by Django 5.0.2 on 2024-03-15 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0004_agentproductbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproductbooking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDMapp.agentproduct'),
        ),
    ]
