# Generated by Django 5.0.2 on 2024-03-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0004_rename_apartement_productbuy_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbuy',
            name='product',
        ),
        migrations.AlterField(
            model_name='productbuy',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDMapp.product')),
                ('producttable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDMapp.productbuy')),
            ],
        ),
        migrations.AddField(
            model_name='productbuy',
            name='items',
            field=models.ManyToManyField(through='IDMapp.ProductItem', to='IDMapp.product'),
        ),
    ]
