# Generated by Django 5.0.2 on 2024-03-22 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0005_remove_productbuy_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbuy',
            name='items',
        ),
        migrations.AddField(
            model_name='productbuy',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IDMapp.product'),
        ),
        migrations.AddField(
            model_name='productbuy',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
