# Generated by Django 5.0.1 on 2024-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0005_agentproduct_catgory_agentproduct_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeededProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.URLField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('catgory', models.CharField(choices=[('bookshelves', 'Bookshelves'), ('centertable', 'Centertable'), ('lcd display unit', 'LCD Display Unit'), ('living-dining-partition', 'Living-Dining Partition'), ('prayer unit', 'Prayer Unit'), ('shoe rack', 'Shoe Rack'), ('sofa and single chairs', 'Sofa and Single Chairs'), ('bed', 'Bed'), ('dressing unit', 'Dressing Unit'), ('wardrobe', 'Wardrobe'), ('bar counter', 'Bar Counter'), ('crockery shelf', 'Crockery Shelf'), ('dining chair', 'Dining Chair'), ('dining table', 'Dining Table'), ('wash', 'Wash'), ('study unit', 'Study Unit'), ('wardrobe cum study table', 'Wardrobe Cum Study Table')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='Category',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bedroom', 'Bed Room'), ('bathroom', 'Bath Room'), ('diningroom', 'Dining Room'), ('bathroom', 'Bathroom'), ('kids room', 'Kids Room')], max_length=100),
        ),
    ]
