# Generated by Django 5.0.2 on 2024-03-05 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0006_neededproducts_alter_home_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproduct',
            name='agent',
        ),
        migrations.AddField(
            model_name='agentproduct',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='agent_photos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'customer'), ('Agent', 'agent')], default='customer', max_length=20, null=True),
        ),
    ]
