# Generated by Django 5.0.2 on 2024-03-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0007_remove_agentproduct_agent_agentproduct_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproduct',
            name='quantity',
        ),
    ]
