# Generated by Django 5.0.2 on 2024-03-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0008_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='IDMapp.cartbuy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDMapp.cart')),
            ],
        ),
    ]
