# Generated by Django 5.0.2 on 2024-03-25 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0009_cartbuyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproductbooking',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
