# Generated by Django 5.0.2 on 2024-03-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0011_rename_phone_number_cartbuy_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbuy',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartbuy',
            name='name',
        ),
        migrations.AlterField(
            model_name='cartbuy',
            name='apartment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartbuy',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartbuy',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='CartBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='IDMapp.cartbuy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDMapp.product')),
            ],
        ),
    ]
