# Generated by Django 5.0.2 on 2024-03-26 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0012_remove_cartbuy_items_remove_cartbuy_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbuy',
            old_name='contact_no',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='cartbuy',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cartbuy',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartbuy',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IDMapp.cart'),
        ),
        migrations.AlterField(
            model_name='cartbuy',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartbuy',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
