# Generated by Django 5.0.2 on 2024-03-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0013_rename_contact_no_cartbuy_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbuy',
            name='product',
        ),
    ]
