# Generated by Django 5.0.2 on 2024-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0014_remove_cartbuy_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200, null=True)),
                ('apartment', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cartbuy',
            name='product',
            field=models.ManyToManyField(to='IDMapp.cartitem'),
        ),
    ]
