# Generated by Django 5.0.2 on 2024-03-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDMapp', '0015_cart_buy_cartbuy_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_buy',
            name='phone_no',
        ),
    ]
